import os
from translate import Translator
from keep_alive import keep_alive
from discord.ext import commands
import sys, traceback
import discord
#Bot icon provided by Unsplash Photos

bot = commands.Bot(
	command_prefix="!",  # Bot prefix
	case_insensitive=True  # Commands aren't case-sensitive
)

bot.author_ids = [318166584214552576, # spectral
									770057013048508426, # mahima
									575451250703859722, # bucketpotato
									340161311264604162  # cinnar
									]  

@bot.event 
async def on_ready():  # When the bot is ready
		print("I'm in")
		print(bot.user)  # Prints the bot's username and identifier
		await bot.change_presence(activity=discord.Game(name='prefix:! type !help for assistance'))

bot.remove_command('help') #removes autogenerated help command so we can write a more personalized one

@bot.event
async def on_command_error(ctx, error):
    if isinstance(error, commands.errors.CheckFailure):
        pass
    else:
        print('Ignoring exception in command {}:'.format(ctx.command), file=sys.stderr)
        traceback.print_exception(type(error), error, error.__traceback__, file=sys.stderr)


extensions = [
	'cogs.cog_example',
	'cogs.translate_cog',
	'cogs.shenanigans',
	'cogs.quotes'
]

if __name__ == '__main__':  # Ensures this is the file being ran
	for extension in extensions:
		print("loading", extension)
		bot.load_extension(extension)  # Loades every extension.

keep_alive()  # Starts a webserver to be pinged.
token = os.environ.get("DISCORD_BOT_SECRET") 
bot.run(token)  # Starts the bot